### ISSUE TITLE
Cant get it working

### ISSUE THREAD

**Issue by sajov** [pudility/jasper-osx#1]
Hi there, thanks for sharing this tutorial!!!

i guess i followed your instructions correct but at least i cant start, getting following error

```
./jasper.py --debug                                                                                                                                                                        [±master ●●]
Traceback (most recent call last):
  File "./jasper.py", line 12, in <module>
    from client import tts
  File "/Users/sajov/Documents/Dev/Research/jasper-client/client/tts.py", line 41, in <module>
    import diagnose
  File "/Users/sajov/Documents/Dev/Research/jasper-client/client/diagnose.py", line 9, in <module>
    import pip.req
ImportError: No module named req
```

I'am not familar with python, pip ... have had trouble with numpy version
Any suggestions? thx

**Comment by mattbilodeau** [comment]
sudo python -m pip install --upgrade pip==9.0.3

to fix that error.

then I updated locations on my profile.yml
pocketsphinx:
  fst_model: '/Users/Username/phonetisaurus/g014b2b.fst'                     
  hmm_dir: '/usr/local/Cellar/cmu-pocketsphinx/0.8/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k'

I'd say give it a shot,  this is an old issue so you might have have figured that out or  given up.  but it might help someone in the future.
